### ISSUE TITLE
[1.16.4] Machine Infuser ONLY accepts Dimensional Shards from RFToolsBase, no other Dimensional Shards

### ISSUE THREAD

**Issue by kil0byt3** [McJtyMods/RFToolsBase#34]
For instance, shards from [Emendatus Enigmatica](https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica). 

If I understand correctly how 1.16 works, can be solved with adding a tag requirement to the Machine Infuser, rather than only allowing a specific item (aka OreDict). 

Pictures:

Emendatus Enigmatica item does not go in:
![image](https://user-images.githubusercontent.com/39413400/103708358-5027aa00-4f65-11eb-945f-84466609f6b7.png)

RFToolsBase item does: 
![image](https://user-images.githubusercontent.com/39413400/103708400-60d82000-4f65-11eb-9f8b-301a4e5b0f22.png)

Tags for both items:
![image](https://user-images.githubusercontent.com/39413400/103708513-8a914700-4f65-11eb-9e82-47300d52cbd2.png)

**Comment by McJty** [comment]
Hmm this is a bit intentional. I don't want anything else to be accepted here. Those other items (whatever they are) are not supposed to be dimensional shards

**Comment by merlerm** [comment]
What that mod is trying to do is add custom ores, so that it can have ores with the correct stone texture next to any kind of stone. That's the reason why it introduces its own dimensional shard ore and item, intended to be exactly the same as regular shards but self contained in the oregen mod, that's why it'd be nice to have them go in there. I don't see the harm in it?

**Comment by McJty** [comment]
I'm going to implement this but on my own tag rftoolsbase:shards as this is a very specific item for RFTools

**Comment by NielsPilgaard** [comment]
Sounds good 👍 will this be for 1.16.5 or just 1.18.2?

**Comment by McJty** [comment]
Both
