### ISSUE TITLE
World gen options not working properly

### ISSUE THREAD

**Issue by Nevrai** [McJtyMods/RFToolsBase#86]
I had the ore chances and vein size of RFTools Nether dimensional shard ore both set to 3, but they were generating very commonly in vein sizes of upwards of six or seven ores. It seems like these options are not working properly.

* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest for 1.18.2)
* **RFTools Base:** 3.0.11 (latest for 1.18.2)

**Comment by Kanzaji** [comment]
Seems to be happening for 1.19.2 as well, tried to disable ore generation with no success.

- Minecraft: 1.19.2
- Forge: 43.2.3
- RFTools Base: 1.19.1-4.0.4

**Comment by McJty** [comment]
yes, those config options actually don't work. They are even gone in the last version of 1.19.2 because there is no way to do this with configs (no proper way that is). What you need to do is use a (small) datapack to override the ore generation.

Basically  you have to make a datapack similar to this:

https://github.com/McJtyMods/RFToolsBase/tree/1.19/src/main/resources/data/rftoolsbase/worldgen

**Comment by TheDeviantCrafter** [comment]
In case anyone else runs into this issue, here's a datapack to disable dimensional shard ore:
[rftoolsbase.zip](https://github.com/McJtyMods/RFToolsBase/files/14338621/rftoolsbase.zip)
